openapi: 3.0.0
info:
  title: Orion Boilerplate API
  description: Boilerplate API for various features
  version: 1.0.0
servers:
- url: http://localhost:3000
security:
- bearerAuth: []
paths:
  /auth/login:
    post:
      summary: User login
      operationId: authLoginPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth_login_body'
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
      x-swagger-router-controller: Default
  /auth/register:
    post:
      summary: User registration
      operationId: authRegisterPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth_register_body'
      responses:
        "201":
          description: Successful registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
      x-swagger-router-controller: Default
  /users/{userId}:
    get:
      summary: Get user by ID
      operationId: usersUserIdGET
      parameters:
      - name: userId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      x-swagger-router-controller: Default
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
      example:
        name: name
        id: id
        email: email
    auth_login_body:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    inline_response_200:
      type: object
      properties:
        token:
          type: string
      example:
        token: token
    auth_register_body:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        name:
          type: string
    inline_response_201:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        name:
          type: string
      example:
        name: name
        id: id
        email: email
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
